Name: custom hava build

on:
   push:
     branches:
        - main:
 jobs:
 build: 
 runs-on: ubuntu-latest

 steps:
      - name: Checkout code
      run: |
         git clone https://github.com/S{{ github.respository }} /tmp/repo
         mv /tmp/repo/* "$(( github.workspace }}"

    - name: Install jave 17
     run: |
      sudo apt update
      sudo apt instal -y openjdk-17-jdk

    - name: Install maven
       run: |
        sudo apt install maven
        echo "S(mvn -version)"
     - name: build
       run: mvn build

     - name: test
       run: mvn test
         
